config/routes.rb
Rails.application.routes.draw do

  mount WeixinRailsMiddleware::Engine, at: "/"
  get 'store/index', as: 'store'

  resources :users do
    member do
      get :followers, :orders, :rewards
    end
  end

  resources :organizations do
    resources :products, shallow: true
    member do
      get :aviliible_invite_codes, :angels, :partners, :members, :vips
    end  
  end

  resources :sessions,        only: [:new, :create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :products
  resources :store
  resources :carts
  resources :line_items
  resources :orders
  resources :rewards

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/docs',    to: 'static_pages#docs',    via: 'get'

  mount API => '/'
  

end

app/views/shared/_catalog.html.erb
<% if @products.any? %>
  <ol class="catalog">
    <%= render partial: 'shared/catalog_item', collection: @products %>
  </ol>
  <%= will_paginate @products %>
<% end %>

app/views/shared/_catalog_item.html.erb
<li id="<%= catalog_item.id %>">
  <%= link_to image_for(catalog_item, size: '70'), catalog_item %>
    <h3>
      <%= link_to catalog_item.name, catalog_item %>
    </h3>
    <span class="content"><%= sanitize(catalog_item.description) %><br></span>
    <div class="price_line">
      <span class="price"><%= number_to_currency(catalog_item.price, unit: '¥ ') %></span>
      <%= button_to '加入购物车', line_items_path(product_id: catalog_item), class: "btn btn-warning btn-xs", remote: true %>
    </div>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      本页面出现 <%= object.errors.count %> 项错误.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "发布新微博...", class: "form-control" %>
  </div>
  <%= f.submit "发布", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(@user) %>">
  <%= gravatar_for @user, size: 52 %>
</a>
<h1>
  <%= @user.name %>
</h1>
<span>
  <%= link_to "修改帐户信息", edit_user_path(@user) %>
</span>

<span>
  
</span>

app/views/shared/_user_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.member.followers.count %>
    </strong>
    粉丝
  </a>

  <a href="<%= orders_user_path(@user) %>">
    <strong id="orders" class="stat">
      <%= @user.member.orders.count %>
    </strong>
    订单
  </a>

  <a href="<%= rewards_user_path(@user) %>">
    <strong id="rewards" class="stat">
      <%= @user.member.rewards.count %>
    </strong>
    返利
  </a>
</div>