config/routes.rb
Rails.application.routes.draw do

  mount WeixinRailsMiddleware::Engine, at: "/"
  get 'store/index', as: 'store'

  resources :users do
    member do
      get :followers, :orders, :rewards
    end
  end

  resources :organizations do
    resources :products, shallow: true
    member do
      get :aviliible_invite_codes, :angels, :partners, :members, :vips
    end  
  end

  resources :sessions,        only: [:new, :create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :products
  resources :store
  resources :carts
  resources :line_items
  resources :orders
  resources :rewards

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/docs',    to: 'static_pages#docs',    via: 'get'

  mount API => '/'
  

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  # It will auto generate weixin token and secret
  #include WeixinRailsMiddleware::AutoGenerateWeixinTokenSecretKey

  has_many :members, dependent: :destroy
  has_many :users, through: :members
  has_many :products
  has_many :orders
  # 自定义菜单
  has_many :diymenus, dependent: :destroy

  # 当前公众账号的所有父级菜单
  has_many :parent_menus, ->{includes(:sub_menus).where(parent_id: nil, is_show: true).order("sort").limit(3)}, class_name: "Diymenu", foreign_key: :organization_id

  belongs_to :created_by_user, class_name: "User", foreign_key: "created_by"
  belongs_to :updated_by_user, class_name: "User", foreign_key: "updated_by"

  default_scope { order('name') }

  validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
  validates :capacity, numericality: { greater_than_or_equal_to: 100, less_than_or_equal_to: 5000, only_integer: true}
  validates :level, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 6, only_integer: true}
  #validates :rate1, numericality: { greater_than_or_equal_to: 100, less_than_or_equal_to: 5000, only_integer: true}
  validates :created_by, presence: true

  #serialize :rates, Hash

  after_initialize :default_values
  after_create :create_master
  after_save :create_invite_codes_for_angels

  def master
    members[0].nil? ? create_master : members[0]
  end


  def aviliible_invite_codes
    members.where("depth = 2 and user_id is null")
  end

  def registered_angels
    members.where("depth = 2 and user_id is not null")
  end

  def registered_partners
    members.where("role = ? and user_id is not null", Member.roles[:partner])
  end

  def registered_members
    members.where("role = ? and user_id is not null", Member.roles[:member])
  end

  def registered_vips
    members.where("role = ? and user_id is not null", Member.roles[:vip])
  end


  def rate
    return 0    
  end

  def levels_for_scoring
    # if rate6 > 0
    #   sl = 6
    # elsif rate5 > 0    
    #   sl = 5 
    # elsif rate4 > 0
    #   sl = 4
    # elsif rate3 > 0
    #   sl = 3
    # elsif rate2 > 0
    #   sl = 2
    # elsif rate1 > 0
    #   sl = 1
    # else
    #   sl = 0
    # end
    return 2
  end

  def sales_total
    #orders.select("sum(price) as sales_total").group("date(created_at)")
    orders.sum(:total)
  end

  def build_menu
    Jbuilder.encode do |json|
      json.button (parent_menus) do |menu|
        json.name menu.name
        if menu.has_sub_menu?
          json.sub_button(menu.sub_menus) do |sub_menu|
            json.type sub_menu.type
            json.name sub_menu.name
            sub_menu.button_type(json)
          end
        else
          json.type menu.type
          menu.button_type(json)
        end
      end
    end
  end

  def generate_weixin_menu
    # 结合: https://github.com/lanrion/weixin_authorize(建议选用此gem的Redis存access_token方案)
    weixin_client = WeixinAuthorize::Client.new(app_id, weixin_secret_key)
    # byebug
    if weixin_client.is_valid?
      menu = build_menu
      result = weixin_client.create_menu(menu)
      url = weixin_client.create_qr_limit_scene(scene_str: invite_code)
      user_info = weixin_client.user('ot_JAs5Xv1QBVOtfOSP5O2Q5CI3g')
      # byebug
      #  Rails.logger.debug(result["errmsg"]) if result["errcode"] != 0
    end
    #redirect_to organization_diymenus_path(@organization)
  end

  private
    def default_values
      if self.new_record?
        # values will be available for new record forms.
        self.capacity ||= 100 
        self.invite_code ||= ''
        self.level ||= 0  
        self.period ||= 4
      end
    end

    def create_master
      members.create!(invite_code: self.invite_code, depth: 1)
    end

    def create_invite_codes_for_angels
      angels = self.capacity - members.count + 1
      master = members[0] unless members[0].nil? 
      angels.times do 
      members.create!(parent_id: master.id,
  	                  organization_id: self.id,
  	                  invite_code: Member.create_invite_code,
                      role: Member.roles[:angel],
  	                  depth: 2
  	                 )
        end
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  
  #before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  #before_action :master_user,  only: [:edit, :update]
  #before_action :admin_user,     only: [:destroy]
  before_action :set_organization, only: [:show, :edit, :update, :destroy, :generate_menu]

  def new
    @organization = Organization.new
  end

  def index
    @organizations = Organization.paginate(page: params[:page])
  end

  def show
  end

  def create
    @organization = current_user.organizations.build(organization_params)
    if @organization.save
      flash[:success] = "推客群创建成功!"
      redirect_to @organization
    else
      render 'new'
    end
  end

  def edit
    @organization.updated_by = current_user.id
  end

  def update
    @organization.updated_by = current_user.id
    if @organization.update_attributes(organization_params)
      flash[:success] = '推客群属性已更新！'
      redirect_to @organization
    else
      render 'edit'
    end
  end

  def destroy
    @organization.destroy
    flash[:success] = "推客群已被删除！"
    redirect_to organizations_url
  end

  def angels
    @title = "天使"
    @organization = Organization.find(params[:id])
    @members = @organization.registered_angels.paginate(page: params[:page])
    render 'show_members'
  end

  def partners
    @title = "伙伴"
    @organization = Organization.find(params[:id])
    @members = @organization.registered_partners.paginate(page: params[:page])
    render 'show_members'
  end

  def vips
    @title = "金牌会员"
    @organization = Organization.find(params[:id])
    @members = @organization.registered_vips.paginate(page: params[:page])
    render 'show_members'
  end

  def members
    @title = "会员"
    @organization = Organization.find(params[:id])
    @members = @organization.registered_members.paginate(page: params[:page])
    render 'show_members'
  end

  def aviliible_invite_codes
    @title = "天使邀请码"
    @organization = Organization.find(params[:id])
    @members = @organization.aviliible_invite_codes.paginate(page: params[:page])
    render 'show_members'
  end


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :contract, :invite_code, :logo_url, :capacity, :level, :period, 
                                           :rate1, :rate2, :rate3, :rate4, :rate5, :rate6, 
                                           :created_by, :updated_by)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper

  def logo_for(organization, options = { size: '80' })
    image_tag(organization.logo_url, alt: organization.name, size: options[:size], class: "gravatar")
  end

end

app/views/organizations/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="form-group">
	<%= f.label :name, '名称：', class: "control-label" %>
	<%= f.text_field :name, readonly: !current_user.admin?, class: "form-control" %>

	<%= f.label :contract, '合同号：', class: "control-label" %>
	<%= f.text_field :contract, readonly: !current_user.admin?, class: "form-control" %>

	<%= f.label :invite_code, '群管理员邀请码：', class: "control-label" %>
	<%= f.text_field :invite_code, readonly: true, class: "form-control" %>	

	<% if !current_user.admin? && current_member.master? %>

		<%= f.label :logo_url, 'Logo 地址：', class: "control-label" %>
		<%= f.text_field :logo_url, class: "form-control" %>

		<%= f.label :capacity, '天使推客总数上限（100 — 5000 人）：', class: "control-label" %>
		<%= f.text_field :capacity, value: 100, class: "form-control" %>

		<%= f.label :period, '返利结算周期：', class: "control-label" %>
		<%= f.select :period, options_for_select({'天' => 1, '周' => 2, '月' => 3, '季度' => 4, '半年' => 5, '年' => 6}, 4) %>

		<%= f.label :app_id, '应用ID：', class: "control-label" %>
		<%= f.text_field :app_id, class: "form-control" %>

		<%= f.label :weixin_secret_key, '微信应用密钥：', class: "control-label" %>
		<%= f.text_field :weixin_secret_key, class: "form-control" %>

		<%= f.label :weixin_token, '微信令牌：', class: "control-label" %>
		<%= f.text_field :weixin_token, class: "form-control" %>	

		<%= f.label :encoding_aes_key, '消息加解密密钥：', class: "control-label" %>
		<%= f.text_field :encoding_aes_key, class: "form-control" %>
		
	<% end %>
 </div>

app/views/organizations/_organization.html.erb
<tr>
  <td><%= logo_for(organization) %></td>
  <td><%= link_to organization.name, organization %></td>
  <td><%= organization.contract %></td>
  <td><%= organization.invite_code %></td>
  <td><%= link_to organization.members[0].name, organization.members[0].user unless organization.members[0].user.nil? %></td>
  <td><%= organization.members.where('user_id is not null and parent_id is not null').count %></td>
  <td><%= organization.products.count %></td>
  <td><%= weixin_engine.weixin_server_url(organization.weixin_secret_key) %></td>
  <td><%= organization.weixin_token %></td>
  <td><%= organization.created_at.strftime("%Y-%-m-%-d") %> </td>
  <td>
    <%= link_to '查看', organization_path(organization) %><br>
    <%= link_to '编辑', edit_organization_path(organization) %><br>
    <%= link_to '删除', organization_path(organization), method: :delete, data: { confirm: '确定删除吗？' } %>
  </td>
</tr>

app/views/organizations/_stats.html.erb
<% @organization ||= current_user.member.organization %>
<div class="stats">
  <% if @organization.aviliible_invite_codes.count > 0 %>
    <a href="<%= aviliible_invite_codes_organization_path(@organization) %>">
      <strong id="angels" class="stat">
        <%= @organization.aviliible_invite_codes.count %>
      </strong>
      天使邀请码
    </a>
  <% end %>
  <a href="<%= angels_organization_path(@organization) %>">
    <strong id="angels" class="stat">
      <%= @organization.registered_angels.count %>
    </strong>
    天使
  </a>
  <a href="<%= partners_organization_path(@organization) %>">
    <strong id="partners" class="stat">
      <%= @organization.registered_partners.count %>
    </strong>
    伙伴
  </a>
  <!--<a href="<%= vips_organization_path(@organization) %>">
    <strong id="vips" class="stat">
      <%= @organization.registered_vips.count %>
    </strong>
    金牌会员
  </a>-->
  <a href="<%= members_organization_path(@organization) %>">
    <strong id="members" class="stat">
      <%= @organization.registered_members.count + @organization.registered_vips.count %>
    </strong>
    会员
  </a>
</div>

app/views/organizations/edit.html.erb
<% provide(:title, "编辑推客群") %>
<h1>修改推客群设置</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@organization) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "保存修改", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/organizations/index.html.erb
<% provide(:title, '推客群列表') %>
<h1>推客群列表</h1>

<%= will_paginate previous_label: '上一页', next_label: '下一页' %>
<table class="table table-striped">
  <tr>
    <th></th>
    <th>名称</th>
    <th>合同号</th>
    <th>注册码</th>
    <th>管理员</th>
    <th>会员总数</th>
    <th>商品总数</th>
    <th>URL</th>
    <th>Token</th>
    <th>创建时间</th>
    <th><%= link_to '新增', new_organization_path %></th>
  </tr>
  <tbody>
	  <ul class="organizations">
	    <%= render @organizations %>
	  </ul>
  </tbody>
</table>
<%= will_paginate previous_label: '上一页', next_label: '下一页' %>
<p><%= link_to '新增', new_organization_path %></p>

app/views/organizations/new.html.erb
<% provide(:title, '推客群') %>
<h1>推客群</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@organization) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
	    <div class="form-group">
		  <%= f.label :name, '名称：', class: "control-label" %>
		  <%= f.text_field :name, readonly: !current_user.admin?, class: "form-control" %>

		  <%= f.label :contract, '合同号：', class: "control-label" %>
		  <%= f.text_field :contract, readonly: !current_user.admin?, class: "form-control" %>

		  <%= f.label :invite_code, '群管理员邀请码：', class: "control-label" %>
		  <%= f.text_field :invite_code, value: invite_codes[0], readonly: true, class: "form-control" %>
	    </div>
      <%= f.submit "新建推客群", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/organizations/show.html.erb
<% provide(:title, @organization.name) %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <a href="<%= edit_organization_path(@organization) %>">
        <%= logo_for(@organization, size: '80') %>
      </a>
      <h1>
        <%= @organization.name %>
      </h1>
      <span>
        <%= link_to "修改群设置", edit_organization_path(@organization) %>
      </span>
    </section> 
    <section>
      <%= render 'stats' %>
    </section> 
    <section>
      <span>销售收入：<%= number_to_currency(@organization.sales_total, unit: '¥ ') %></span>
    </section>        
  </aside>

  <div class="col-md-8">
    <h3>最近销售</h3>
    <table class="table table-striped">
      <tr>
        <th>订购时间</th>
        <th>订单</th>
        <th>会员</th>
        <th>总金额</th>
      </tr>
      <% if @organization.orders.any? %>
        <tbody>
          <ul class="orders">
            <% @organization.orders.each do |order| %>
              <tr>
                <td><%= order.created_at.strftime("%Y-%-m-%-d") %></td>
                <td><%= link_to order.id.to_s, order %> 号订单</td>
                <td><%= order.member.name %></td>
                <td><strong><%= number_to_currency(order.total, unit: '¥ ') %></strong></td>
              </tr>
            <% end %>
          </ul>
        </tbody>
      <% end %>     
    </table>
  </div>
</div>
	

app/views/organizations/show_members.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <a href="<%= edit_organization_path(@organization) %>">
        <%= logo_for(@organization, size: '80') %>
      </a>
      <h1>
        <%= @organization.name %>
      </h1>
      <span>
        <%= link_to "修改群设置", edit_organization_path(@organization) %>
      </span>
    </section>
    <section>
      <%= render 'stats' %>
      <% if @members.any? %>
        <div class="user_avatars">
          <% @members.each do |member| %>
            <%= link_to gravatar_for(member.user, size: 32), member.user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>

  <div class="col-md-8">
    <h3><%= @title %></h3>
    <table class="table table-striped">
      <tr>
        <th></th>
        <th>姓名</th>
        <th>帐号</th>
        <th>邀请码</th>
        <th>返利</th>
        <th>等级</th>
        <th>下级</th>
        <th>订单</th>
        <th>注册时间</th>
      </tr>
      <% if @members.any? %>
        <tbody>
          <ul class="members">
          	<% @members.each do |member| %>
              <tr>
                <td><%= gravatar_for(member.user) %></td>
                <td><%= link_to member.name, member.user.nil? ? '' : member.user %></td>
                <td><%= member.user.nil? ? '' : member.user.email %></td>
                <td><%= member.invite_code %></td>
                <td><%= member.points %></td>
                <td><%= member.depth - 1 %></td>
                <td><%= member.descendants.count %></td>
                <td><%= member.orders.count %></td>
                <td><%= member.created_at.strftime("%Y-%-m-%-d") %></td>
              </tr>
            <% end %>
          </ul>
        </tbody>
      <% end %>     
    </table>
    <%= will_paginate(@members, previous_label: '上一页', next_label: '下一页') %>
  </div>
</div>