config/routes.rb
Rails.application.routes.draw do

  mount WeixinRailsMiddleware::Engine, at: "/"
  get 'store/index', as: 'store'

  resources :users do
    member do
      get :followers, :orders, :rewards
    end
  end

  resources :organizations do
    resources :products, shallow: true
    member do
      get :aviliible_invite_codes, :angels, :partners, :members, :vips
    end  
  end

  resources :sessions,        only: [:new, :create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :products
  resources :store
  resources :carts
  resources :line_items
  resources :orders
  resources :rewards

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/docs',    to: 'static_pages#docs',    via: 'get'

  mount API => '/'
  

end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :created_by_user, class_name: "User", foreign_key: "created_by"
  belongs_to :updated_by_user, class_name: "User", foreign_key: "updated_by"
  belongs_to :organization, counter_cache: true

  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item
  
  default_scope { order('organization_id').order('name') }
  scope :by_organization, ->(org_id) {where(organization_id: org_id).order('name')} 

  validates :name, :description, :image_url, presence: true
  validates :name, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
  validates :price, numericality: {greater_than_or_equal_to: 0.01}  
  #validates :image_url, allow_blank: true, format: {
  #  with:    %r{\.(gif|jpg|png)\Z}i,
  #  message: 'must be a URL for GIF, JPG or PNG image.' }
  validates :created_by, presence: true

  def self.latest 
    Product.order(:updated_at).last
  end

  def rate
    rate = Array.new(7, 0)
    rate[0] = rate0
    rate[1] = rate1
    rate[2] = rate2
    rate[3] = rate3
    rate[4] = rate4
    rate[5] = rate5
    rate[6] = rate6
    return rate    
  end
 
  def angel_rate
    return rate0
  end
  
  def vip_rate
    return rate6
  end

  def partner_rate
    rate = Array.new(6, 0)
    rate[0] = 0
    rate[1] = rate1
    rate[2] = rate2
    rate[3] = rate3
    rate[4] = rate4
    rate[5] = rate5
    return rate 
  end

  def levels_for_scoring
    sl = 0
    if rate5 > 0    
      sl = 5 
    elsif rate4 > 0
      sl = 4
    elsif rate3 > 0
      sl = 3
    elsif rate2 > 0
      sl = 2
    elsif rate1 > 0
      sl = 1 
    end
  end
    
  private
    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item 
      if line_items.empty?
        return true 
      else
        errors.add(:base, 'Line Items present')
        return false 
      end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def new
    @product = Product.new
  end

  def index
    @organization = params[:organization_id]
    if @organization.nil?
      # 管理员查看产品列表
      if !current_user.nil?
        if current_user.admin?
          @products = Product.paginate(page: params[:page])
        else
          @organization = current_user.member.nil? ? 0 : current_user.member.organization_id
          @products = Product.by_organization(@organization).paginate(page: params[:page]) 
        end
      end
    else
      # 显示当前组织的产品列表
      # 处理形式为http://localhost:3000/organizations/1/products的URL的路由
      @products = Product.by_organization(@organization).paginate(page: params[:page]) 
    end
  end

  def show
  end

  def create
    @product = current_user.member.organization.products.build(product_params)
    @product.created_by = current_user.id if current_member.master?
    if @product.save
      flash[:success] = "商品创建成功!"
      redirect_to @product
    else
      render 'new'
    end
  end

  def edit
    @product.updated_by = current_user.id
  end

  def update
    @product.updated_by = current_user.id
    if @product.update_attributes(product_params)
      flash[:success] = '商品属性已更新！'
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "商品已被删除！"
    redirect_to products_url
  end


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:organization_id, :name, :description, :image_url, :qualify,
                                      :rate0, :rate1, :rate2, :rate3, :rate4, :rate5, :rate6, 
                                      :price, :retail, :wholesale, :created_by, :updated_by)
    end

    def set_product
      @product = Product.find(params[:id])
    end
end

app/helpers/products_helper.rb
module ProductsHelper

  def image_for(product, options = { size: '100' })
    image_tag(product.image_url, alt: product.name, size: options[:size], class: "gravatar")
  end

  def qrcode_for_product(product, options = { size: 50 })
    img_name = "u" + product.id.to_s + ".png"
    product_url = "http://wtk.meeket.com/products/" + product.id.to_s
    size = options[:size] * 3
    png = RQRCode::QRCode.new(product_url, size: 4, level: :h).to_img.resize(size, size)

    url = "./app/assets/images/" + img_name
    png.save(url)
    name = product.nil? ? '' : product.name
    image_tag(img_name, alt: name, class: "gravatar")
  end

end

app/views/products/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :name, '名称：', class: "control-label" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description, '描述：', class: "control-label" %>
  <%= f.text_area :description, rows: 10, class: "form-control" %>

  <%= f.label :image_url, ' 图片：', class: "control-label" %>
  <%= f.text_field :image_url, class: "form-control" %>

  <%= f.label :price, '现价：', class: "control-label" %>
  <%= f.text_field :price, class: "form-control" %>

  <%= f.label :retail, '零售价：', class: "control-label" %>
  <%= f.text_field :retail, class: "form-control" %> 

  <%= f.label :wholesale, '加盟价：', class: "control-label" %>
  <%= f.text_field :wholesale, class: "form-control" %>
  
  <%= f.check_box :qualify %>
  <%= f.label :qualify, '通过购买此商品获得加盟资格', class: "control-label" %>

  <br><br>

  <%= f.label :rate1, '返利计提：', class: "control-label" %> 	
  <table class="table table-striped table-bordered">
    <tr> 
      <th>等级间隔</th>
      <th>计提百分比<br>（ ％ ）</th>
    </tr> 
  
    <!--<tr> 
      <td>天使特权（基于加盟价）</td>
      <td><%= f.text_field :rate0, class: "form-control" %></td>
    </tr>-->

    <tr> 
      <td>1 级</td>
      <td><%= f.text_field :rate1, class: "form-control" %></td>
    </tr>

    <tr> 
      <td>2 级</td>
      <td><%= f.text_field :rate2, class: "form-control" %></td>
    </tr>

    <tr> 
      <td>3 级</td>
      <td><%= f.text_field :rate3, class: "form-control" %></td>
    </tr>
  <!--	
    <tr> 
      <td>4 级</td>
      <td><%= f.text_field :rate4, class: "form-control" %></td>
    </tr>

    <tr> 
      <td>5 级</td>
      <td><%= f.text_field :rate5, class: "form-control" %></td>
    </tr>

    <tr> 
      <td>金牌会员特权（基于实际消费额）</td>
      <td><%= f.text_field :rate6, class: "form-control" %></td>
    </tr>  -->
  </table>
</div>

app/views/products/_product.html.erb
<tr>
  <td><%= image_for(product) %></td>
  <td>
    <dl>
      <dt><%= link_to product.name, product %></dt>
      <dd><%= truncate(strip_tags(product.description), length: 200) %></dd>
      <% if !current_user.nil? && current_user.admin? %>
        <br><br>
        <dt><%= link_to product.organization.name, product.organization %></dt>
      <% end %>
    </dl>
  </td>
  <td><%= number_to_currency(product.price, unit: '¥ ') %></td>
  <% if !current_user.nil? && (current_user.admin? || current_member.master?) %>
    <td>
      <%= link_to '查看', product_path(product) %><br>
      <%= link_to '编辑', edit_product_path(product) %><br>
      <%= link_to '删除', product_path(product), method: :delete, data: { confirm: '确定删除吗？' } %>
    </td>
  <% end %>
</tr>

app/views/products/edit.html.erb
<% provide(:title, "编辑商品") %>
<h1>修改商品信息</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "保存修改", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<% provide(:title, '商品列表') %>
<h1>商品列表</h1>

<%= will_paginate previous_label: '上一页', next_label: '下一页' %>
<table class="table table-striped">
  <tr>
    <th>商品</th>
    <th>说明</th>
    <th>价格</th>
    <% if !current_user.nil? && !current_user.admin? && current_member.master? %>
      <th>操作</th>
    <% end %>
  </tr>
  <tbody>
	<ul class="products">
	  <%= render @products %>
	</ul>
  </tbody>
</table>
<%= will_paginate previous_label: '上一页', next_label: '下一页' %>
<% if !current_user.nil? && !current_user.admin? && current_member.master? %>
  <p><%= link_to '新增', new_product_path %></p>
<% end %>

app/views/products/new.html.erb
<% provide(:title, '新增商品') %>
<h1>新增商品</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "新建商品", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>

<div class="row">
  <aside class="col-md-4">
    <section>
      <%= image_for(@product) %>
    </section>
    <% if !current_user.nil? && (current_user.admin? || current_member.master?) %> 
      <span><%= link_to "修改商品信息", edit_product_path(@product) %></span>
    <% end %>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
      <div>
        <h3><%= @product.name %></h3>
        <div class="cart_line">
          <!--<% if !current_user.nil? && current_member.member? %>
            <% if @product.retail == @product.price %>
              <span class="price">零售价：<%= number_to_currency(@product.retail, unit: '¥ ') %></span><br>
            <% else %>
              <span class="price">现  价：<%= number_to_currency(@product.retail, unit: '¥ ') %></span><br>
              <span class="price">零售价：<%= number_to_currency(@product.retail, unit: '¥ ') %></span><br>
            <% end %>
          <% else %>
            <span class="price">加盟价：<%= number_to_currency(@product.wholesale, unit: '¥ ') %></span><br>
          <% end %>-->
          <span class="price">价格：<%= number_to_currency(@product.price, unit: '¥ ') %></span><br>
          <% if !current_user.nil? && (current_member.angel? || current_member.member?) %> 
            <%= button_to '加入购物车', line_items_path(product_id: @product), class: "btn btn-warning btn-xs", remote: true %>
          <% end %>
        </div>
        <p><%= sanitize(@product.description) %></p>
      </div>
      <!--<div class="col-md-6 col-md-offset-3">
        <%= qrcode_for_product @product %>
      </div>-->
  </div>
</div>
	