config/routes.rb
Rails.application.routes.draw do

  mount WeixinRailsMiddleware::Engine, at: "/"
  get 'store/index', as: 'store'

  resources :users do
    member do
      get :followers, :orders, :rewards
    end
  end

  resources :organizations do
    resources :products, shallow: true
    member do
      get :aviliible_invite_codes, :angels, :partners, :members, :vips
    end  
  end

  resources :sessions,        only: [:new, :create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :products
  resources :store
  resources :carts
  resources :line_items
  resources :orders
  resources :rewards

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/docs',    to: 'static_pages#docs',    via: 'get'

  mount API => '/'
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.meeket.com">微推客</a>
    北京码客信息技术有限公司
  </small>
  <nav>
    <ul>
      <li><%= link_to "关于",   about_path %></li>
      <li><%= link_to "联系我们", contact_path %></li>
      <li><a href="http://www.meeket.com">最新动态</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"> 
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "微推客", root_path, id: "logo" %>
      <nav>
        <ul class="nav nav-pills">
          <% if signed_in? %>
            <% if current_user.admin? %>
              <li><%= link_to "推客群列表", organizations_path %></li>
              <li><%= link_to "推客列表", users_path %></li>
              <li><%= link_to "商品列表", products_path %></li>
            <% elsif current_member.master? %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">推客群 
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li role="presentation"><%= link_to "查看", current_user.member.organization %></li>
                  <li role="presentation"><%= link_to "设置", edit_organization_path(current_user.member.organization) %></li>
                  <!--<li class="divider"></li>-->
                </ul>
              </li>
              <li><%= link_to "推客成员", users_path %></li> 
              <li><%= link_to "商品清单", products_path %></li>
              <li><%= link_to "全部订单", orders_path %></li> 
              <li><%= link_to "返利", rewards_path %></li>  
            <% else %>
              <li><%= link_to "商品", root_path %></li>
            <% end %>
            <li><%= link_to "我的帐号", edit_user_path(current_user) %></li>
            <li><%= link_to "退出", signout_path, method: "delete" %></li>
            </li>
          <% else %>
            <li><%= link_to "登录", signin_path %></li>
          <% end %>
          <li><%= link_to "帮助", help_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>